# 00 PyTorch Fundamentals

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Check for GPU (should return True)
print(torch.cuda.is_available())

True


# TENSORS shapes and dimensions

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random TENSORS

In [17]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3400, 0.1828, 0.3022, 0.5389],
        [0.9224, 0.7032, 0.7090, 0.0886],
        [0.0020, 0.8127, 0.2122, 0.7709]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

# Zeroes and ones

In [20]:
# Create a tensor of all zeros
zeroes = torch.zeros(size=(3, 4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Range of tensors and tensors-like
https://pytorch.org/docs/2.1/generated/torch.arange.html#torch-arange

In [22]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# range with steps
range_with_steps = torch.arange(start=0, end=1000, step=77)
range_with_steps

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# TENSOR datatypes
https://pytorch.org/docs/2.1/tensors.html

torch.rand()

https://pytorch.org/docs/stable/generated/torch.rand.html#torch-rand

torch.randint()

https://pytorch.org/docs/stable/generated/torch.randint.html#torch-randint

Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [26]:
float_16_tensor = torch.rand(size = (3, 3, 3),
                            dtype = torch.float16,
                            device = 'cuda')

# float32 is default, which is why it doesn't get written
float_32_tensor = torch.rand(size = (3, 3, 3),
                             device = 'cuda')

float_64_tensor = torch.rand(size = (3, 3, 3),
                            dtype = torch.float64,
                            device = 'cuda')

int_16_tensor = torch.randint(high = 10,
                              size = (3, 3, 3),
                              dtype = torch.int16,
                              device = 'cuda')

int_32_tensor = torch.randint(high = 10,
                              size = (3, 3, 3),
                              dtype = torch.int32,
                              device = 'cuda')

int_64_tensor = torch.randint(high = 10,
                              size = (3, 3, 3),
                              dtype = torch.int64,
                              device = 'cuda')

In [27]:
int_64_tensor

tensor([[[1, 0, 1],
         [0, 3, 9],
         [9, 7, 3]],

        [[0, 0, 9],
         [4, 8, 4],
         [7, 1, 6]],

        [[8, 2, 5],
         [6, 5, 6],
         [6, 0, 0]]], device='cuda:0')

## Convert datatypes

In [28]:
int_32_tensor.dtype

torch.int32

In [29]:
# int32 -> float32
int_32_tensor.type(torch.float32).dtype

torch.float32

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
# float32 -> int32
float_32_tensor.type(torch.int32).dtype

torch.int32

# TENSOR attributes

1. datatype - `tensor.dtype`
2. shape - `tensor.shape`
3. device - `tensor.device`

In [32]:
print(f"Datatype of tensor: {int_64_tensor.dtype}")
print(f"Shape of tensor: {int_64_tensor.shape}")
print(f"Device of tensor: {int_64_tensor.device}")

Datatype of tensor: torch.int64
Shape of tensor: torch.Size([3, 3, 3])
Device of tensor: cuda:0


# TENSOR operations

Basic:

! ACHTUNG !

The dims of the tensors must match.

🚫 - ([1, 2, 3]) + ([1, 2])

✅ - ([1, 2, 3]) + ([1, 2, 3])

* Addition
* Subtraction
* Multiplication (element-wise)
* Division

Advanced:
  
* Matrix multiplication (dot product)

## Basic

In [33]:
subj1 = torch.tensor([1, 2, 3])
subj2 = torch.tensor([3, 4, 5])

In [34]:
subj1 + 10

tensor([11, 12, 13])

In [35]:
subj1 + subj2

tensor([4, 6, 8])

In [36]:
subj1 - 10

tensor([-9, -8, -7])

In [37]:
subj1 - subj2

tensor([-2, -2, -2])

In [38]:
subj1 * 10

tensor([10, 20, 30])

In [39]:
subj1 * subj2

tensor([ 3,  8, 15])

In [40]:
subj1 / 10

tensor([0.1000, 0.2000, 0.3000])

In [41]:
subj1 / subj2

tensor([0.3333, 0.5000, 0.6000])

## Advanced - MATRIX multiplication (dot product)
http://matrixmultiplication.xyz/

Rules:
1. Inner dimensions must match

torch.Size([2, 3]) and torch.Size([3, 2])

3 and 3 are matching

<img src="../pycharm/images/0-2.png">

2. The resulting matrix has the shape of the outer dimensions

In [42]:
M1 = torch.tensor([[1, 2, 3],
                   [4, 5, 6]])
M2 = torch.tensor([[7, 8],
                   [9, 10],
                   [11, 12]])

In [43]:
%%time
torch.matmul(M1, M2)

CPU times: user 984 µs, sys: 146 µs, total: 1.13 ms
Wall time: 10.3 ms


tensor([[ 58,  64],
        [139, 154]])

<img src="../pycharm/images/0-1.png">

In [44]:
M2.shape

torch.Size([3, 2])

# TENSORs transpose
Transpose switches the axes or dimensions of a given tensor.

<img src="../pycharm/images/0-3.gif">

In [45]:
T1 = torch.tensor([[1, 2],
                   [3, 4],
                   [5, 6]])
T2 = torch.tensor([[7, 10],
                   [8, 11],
                   [9, 12]])

In [46]:
T2.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [47]:
T2.T.shape

torch.Size([2, 3])

In [48]:
torch.matmul(T1, T2.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [49]:
torch.matmul(T1, T2.T).shape

torch.Size([3, 3])

In [50]:
torch.matmul(T1.T, T2)

tensor([[ 76, 103],
        [100, 136]])

In [51]:
torch.matmul(T1.T, T2).shape

torch.Size([2, 2])

# TENSOR aggregation

In [52]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Min

In [53]:
torch.min(x)

tensor(0)

## Max

In [54]:
torch.max(x)

tensor(90)

## Mean (only float)

In [55]:
torch.mean(x.type(torch.float32))

tensor(45.)

## Sum

In [56]:
torch.sum(x)

tensor(450)

## Argmin

In [57]:
# position of element with minimal value of given tensor
# position are counted from zero
torch.argmin(x)

tensor(0)

## Argmax

In [58]:
# position of element with minimal value of given tensor
# position are counted from zero
torch.argmax(x)

tensor(9)

# Reshaping, viewing, stacking, squeezing, unsqueezing and permuting tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - return a view of the input with dimensions (swapped) in a certain way

In [59]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
x.shape

torch.Size([9])

## Reshape

It will work if the multiplication is always 9

`torch.Size([3, 3])` - 3 * 3 = 9

`torch.Size([9, 1])` - 9 * 1 = 9

`torch.Size([3, 3, 1])` - 3 * 3 * 1 = 9

In [61]:
x_reshaped1 = x.reshape(3, 3)
x_reshaped1

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [62]:
x_reshaped2 = x.reshape(9, 1)
x_reshaped2

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [63]:
x_reshaped2 = x.reshape(3, 3, 1)
x_reshaped2

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])

## View
Changing z changes x (because a view of a tensor shares the same memory as the original)


In [64]:
z = x.view(3, 3, 1)
z

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])

In [65]:
z.shape

torch.Size([3, 3, 1])

## Stack
Stack tensors on top of each other 

In [66]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

## Squeezing

In [68]:
x_reshaped4 = x.reshape(3, 3, 1, 1)
x_reshaped4

tensor([[[[1.]],

         [[2.]],

         [[3.]]],


        [[[4.]],

         [[5.]],

         [[6.]]],


        [[[7.]],

         [[8.]],

         [[9.]]]])

In [69]:
x_reshaped4.shape

torch.Size([3, 3, 1, 1])

In [70]:
x_squeezed = x_reshaped4.squeeze()

In [71]:
# Removed all ones
x_squeezed.shape

torch.Size([3, 3])

## Unsqueezing

In [72]:
x_unsqueezed0 = x_squeezed.unsqueeze(dim=0)
x_unsqueezed0

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [73]:
x_unsqueezed0.shape

torch.Size([1, 3, 3])

In [74]:
x_unsqueezed1 = x_squeezed.unsqueeze(dim=1)
x_unsqueezed1

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])

In [75]:
x_unsqueezed1.shape

torch.Size([3, 1, 3])

In [76]:
x_unsqueezed2 = x_squeezed.unsqueeze(dim=2)
x_unsqueezed2

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])

In [77]:
x_unsqueezed2.shape

torch.Size([3, 3, 1])

## Permute

In [78]:
x_picture = torch.rand(size=(720, 480, 3)) # [height, width, colour_channels]
x_picture.shape

torch.Size([720, 480, 3])

In [79]:
x_permuted0 = x_picture.permute(2, 0, 1)
x_permuted0.shape

torch.Size([3, 720, 480])

In [80]:
# How it works:
# Moving this dim numbers also moves their values
# (0    1    2)
# (720, 480, 3)
#
# So moving like this:
# (2  0    1)
# Will be look like this:
# (3, 720, 480)

In [81]:
# Moving like this:
# (1    0    2)
# Will be like this:
# (480, 720, 3)
x_permuted1 = x_picture.permute(1, 0, 2)
x_permuted1.shape

torch.Size([480, 720, 3])

# Indexing
Selecting data from tensors

In [82]:
x_indexing = torch.arange(1, 10).reshape(1, 3, 3)
x_indexing

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [83]:
x_indexing.shape

torch.Size([1, 3, 3])

In [84]:
x_indexing[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [85]:
x_indexing[0][1]

tensor([4, 5, 6])

In [86]:
x_indexing[0][2][1]

tensor(8)

In [87]:
x_indexing[:, :, 2]

tensor([[3, 6, 9]])

In [88]:
x_indexing[:, 1, 1]

tensor([5])

In [89]:
x_indexing[0, 0, :]

tensor([1, 2, 3])

# PyTorch tensors & NumPy
* Convert NumPy data to PyTorch tensor -> `torch.from.numpy(ndarray)`
* Convert PyTorch tensor to NumPy data -> `torch.Tensor.numpy()`

! ACHTUNG ! - NumPy default dtype is float64

## 1. NumPy -> PyTorch

In [90]:
np_array0 = np.arange(1.0, 8.0)
np_array0

array([1., 2., 3., 4., 5., 6., 7.])

In [91]:
torch_tensor0 = torch.from_numpy(np_array0)
torch_tensor0

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [92]:
torch_tensor0.dtype

torch.float64

In [93]:
# Also dtype changed to float32
torch_tensor1 = torch.from_numpy(np_array0).type(torch.float32)
torch_tensor1

tensor([1., 2., 3., 4., 5., 6., 7.])

In [94]:
torch_tensor1.dtype

torch.float32

## 2. Pytorch -> NumPy

In [95]:
torch_tensor1 = torch.ones(7)
torch_tensor1

tensor([1., 1., 1., 1., 1., 1., 1.])

In [96]:
torch_tensor1.dtype

torch.float32

In [97]:
np_tensor1 = torch_tensor1.numpy()
np_tensor1

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [98]:
np_tensor1.dtype

dtype('float32')

# Reproducibility - random seed

Random seed "flavours" randomess.

In [99]:
random_tensor_A = torch.rand(3, 4)
random_tensor_A

tensor([[0.8197, 0.2084, 0.6240, 0.6944],
        [0.3957, 0.0686, 0.9097, 0.6940],
        [0.3671, 0.3943, 0.7164, 0.2780]])

In [100]:
random_tensor_B = torch.rand(3, 4)
random_tensor_B

tensor([[0.2537, 0.6961, 0.2547, 0.1310],
        [0.8346, 0.5103, 0.1819, 0.2723],
        [0.8129, 0.2017, 0.2925, 0.4460]])

In [101]:
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [102]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [103]:
torch.manual_seed(RANDOM_SEED)
random_tensor_C0 = torch.rand(3, 4)
random_tensor_C0

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [104]:
random_tensor_C1 = torch.rand(3, 4)
random_tensor_C1

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [105]:
torch.manual_seed(RANDOM_SEED)
random_tensor_D0 = torch.rand(3, 4)
random_tensor_D0

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [106]:
random_tensor_D1 = torch.rand(3, 4)
random_tensor_D1

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [107]:
random_tensor_C0 == random_tensor_D0

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [108]:
random_tensor_C1 == random_tensor_D1

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# GPU CUDA

In [109]:
!nvidia-smi

Sat Feb  3 13:10:24 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080        Off | 00000000:01:00.0  On |                  N/A |
|  0%   51C    P0              39W / 200W |    991MiB /  8192MiB |      4%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [110]:
print(torch.cuda.is_available())

True


In [111]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [112]:
# Count number of devices
torch.cuda.device_count()

1

# Putting tensors on GPU (CUDA)

## 1. CPU -> GPU (CUDA)

In [113]:
default_tensor = torch.rand(3, 4)
default_tensor

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])

In [114]:
default_tensor.device

device(type='cpu')

In [115]:
tensor_on_gpu = default_tensor.to(device)
tensor_on_gpu

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]], device='cuda:0')

In [116]:
tensor_on_gpu.device

device(type='cuda', index=0)

## 2. GPU (CUDA) -> CPU

In [117]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])

In [118]:
tensor_back_on_cpu.device

device(type='cpu')