In [13]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

# Check for GPU (should return True)
print(torch.cuda.is_available())

True


# 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on `torch.Tensor`.
* The documentation on `torch.cuda`.


# 2. Create a random tensor with shape (7, 7).

In [2]:
exe0 = torch.rand(7, 7)
exe0

tensor([[0.9526, 0.4821, 0.9081, 0.5578, 0.6190, 0.6979, 0.7425],
        [0.4887, 0.8666, 0.9788, 0.4119, 0.2415, 0.9602, 0.7082],
        [0.5142, 0.9331, 0.2313, 0.1328, 0.3942, 0.5263, 0.6212],
        [0.4553, 0.8690, 0.5941, 0.0067, 0.8243, 0.9618, 0.5596],
        [0.9248, 0.3059, 0.5802, 0.1167, 0.0160, 0.5972, 0.4161],
        [0.0534, 0.1947, 0.9412, 0.1454, 0.2094, 0.8786, 0.7328],
        [0.8802, 0.6485, 0.4679, 0.9762, 0.6135, 0.2783, 0.6064]])

In [3]:
exe0.shape

torch.Size([7, 7])

# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:
exe1 = torch.rand(1, 7)

In [5]:
mm = torch.matmul(exe0, exe1.T)
mm

tensor([[2.0254],
        [1.6799],
        [1.2261],
        [1.8473],
        [0.9788],
        [1.2992],
        [1.6933]])

# 4. Set the random seed to 0 and do 2 & 3 over again

In [6]:
RANDOM_SEED = 0

In [7]:
torch.manual_seed(RANDOM_SEED)
seed_exe0 = torch.rand(7, 7)
seed_exe1 = torch.rand(1, 7)

In [8]:
seed_mm = torch.matmul(seed_exe0, seed_exe1.T)
seed_mm, seed_mm.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [9]:
CUDA_RANDOM_SEED = 1234
torch.cuda.manual_seed(CUDA_RANDOM_SEED)
cuda_seed_exe0 = torch.rand(7, 7)
cuda_seed_exe1 = torch.rand(1, 7)

In [10]:
cuda_seed_mm = torch.matmul(cuda_seed_exe0, cuda_seed_exe1.T)
cuda_seed_mm, seed_mm.shape

(tensor([[1.2239],
         [2.0847],
         [1.9002],
         [0.9408],
         [1.5213],
         [1.3606],
         [0.8780]]),
 torch.Size([7, 1]))

# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [16]:
torch.manual_seed(1234)
exe2 = torch.rand(2, 3)
exe3 = torch.rand(2, 3)

In [17]:
cuda_exe2 = exe2.to(device)
cuda_exe2

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [18]:
cuda_exe3 = exe3.to(device)
cuda_exe3

tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')

# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [21]:
cuda_seed_mm = torch.matmul(cuda_exe2, cuda_exe3.T)
cuda_seed_mm, cuda_seed_mm.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

# 8. Find the maximum and minimum values of the output of 7.

In [23]:
cuda_seed_mm

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [24]:
torch.max(cuda_seed_mm)

tensor(0.5617, device='cuda:0')

In [33]:
torch.min(cuda_seed_mm)

tensor(0.3647, device='cuda:0')

# 9. Find the maximum and minimum index values of the output of 7.

In [34]:
torch.argmax(cuda_seed_mm)

tensor(3, device='cuda:0')

In [35]:
torch.argmin(cuda_seed_mm)

tensor(0, device='cuda:0')

# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [31]:
torch.manual_seed(7)
seed_exe4 = torch.rand(1, 1, 1, 10)
seed_exe4, seed_exe4.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [32]:
seed_exe4_squeezed = seed_exe4.squeeze()
seed_exe4_squeezed, seed_exe4_squeezed.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))